# Generate a C++ source file that embeds binary files as byte arrays.
#
# Usage (script mode):
#   cmake -DOUTPUT=<file.cpp> -DNAMESPACE=<ns> -DINPUTS=<file1;file2;...> -DSYMBOLS=<sym1;sym2;...>
#         -P EmbedResources.cmake
#
# For each input file, an array `<ns>::<sym>[]` of type `unsigned char`
# and a `std::size_t <ns>::<sym>_len` is emitted.

if(NOT OUTPUT OR NOT INPUTS OR NOT SYMBOLS)
    message(FATAL_ERROR "EmbedResources: OUTPUT, INPUTS and SYMBOLS must be set.")
endif()
if(NOT NAMESPACE)
    set(NAMESPACE "Resources")
endif()

list(LENGTH INPUTS _inputs_n)
list(LENGTH SYMBOLS _symbols_n)
if(NOT _inputs_n EQUAL _symbols_n)
    message(FATAL_ERROR "EmbedResources: INPUTS and SYMBOLS must have the same length.")
endif()

set(_content "/* This file is generated by EmbedResources.cmake - do not edit. */\n")
string(APPEND _content "#include <cstddef>\n\n")
string(APPEND _content "namespace ${NAMESPACE}\n{\n")

math(EXPR _last "${_inputs_n} - 1")
foreach(_i RANGE ${_last})
    list(GET INPUTS ${_i} _file)
    list(GET SYMBOLS ${_i} _sym)

    file(READ "${_file}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _byte_len "${_hex_len} / 2")

    # turn "0a1b2c" into "0x0a,0x1b,0x2c,"
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    # wrap lines after 16 bytes for readability (and to stay below compiler line-length limits)
    string(REPEAT "0x[0-9a-f][0-9a-f]," 16 _line_pattern)
    string(REGEX REPLACE "(${_line_pattern})" "    \\1\n" _bytes "${_bytes}")
    # indent and terminate a trailing partial line, if any
    if(_bytes MATCHES "\n([^\n]+)$")
        string(REGEX REPLACE "\n([^\n]+)$" "\n    \\1\n" _bytes "${_bytes}")
    elseif(_bytes AND NOT _bytes MATCHES "\n$")
        set(_bytes "    ${_bytes}\n")
    endif()

    string(APPEND _content "extern const unsigned char ${_sym}[];\n")
    string(APPEND _content "extern const std::size_t ${_sym}_len;\n")
    string(APPEND _content "const unsigned char ${_sym}[] = {\n${_bytes}};\n")
    string(APPEND _content "const std::size_t ${_sym}_len = ${_byte_len};\n\n")
endforeach()

string(APPEND _content "} // namespace ${NAMESPACE}\n")

# only rewrite if the content changed, to avoid needless rebuilds
set(_old "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUTPUT}" "${_content}")
endif()
