#
# Docker file for PoMiDAQ CI
#
FROM ubuntu:noble

# prepare
RUN apt-get update -qq
RUN apt-get install -yq --no-install-recommends eatmydata software-properties-common
RUN add-apt-repository -y ppa:ximion/syntalos
RUN apt-get update -qq

# install build essentials
RUN DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -yq \
    build-essential gcc g++

# install build dependencies
RUN DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -yq --no-install-recommends \
    git-core \
    dpkg-dev \
    devscripts \
    debhelper \
    debspawn \
    libdistro-info-perl \
    cmake \
    ninja-build \
    appstream \
    qt6-base-dev \
    qt6-svg-dev \
    libkf6configwidgets-dev \
    libopencv-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    pybind11-dev \
    python3-dev \
    python3-numpy

# finish
RUN mkdir /build
WORKDIR /build
