name: Build

on: [push, pull_request, workflow_call]

jobs:
  get-version:
    name: Determine revision number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version-numeric: ${{ steps.version.outputs.version-numeric }}

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Determine revision number
      id: version
      run: |
        git_commit=$(git rev-parse --short HEAD)
        git_current_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)
        git_commit_no=$(git rev-list --count "${git_current_tag}..HEAD" 2>/dev/null)
        PMD_VERSION=${git_current_tag#v}; PMD_VERSION=${PMD_VERSION//-/.}
        PMD_VERSION_NUMERIC=$(echo "${git_current_tag}" | sed 's/^v//;s/[^0-9.].*//')
        if [ "$git_commit_no" -gt 0 ]; then
          PMD_VERSION+="+git$git_commit_no"
        fi
        echo "version=${PMD_VERSION}" >> $GITHUB_OUTPUT
        echo "version-numeric=${PMD_VERSION_NUMERIC}" >> $GITHUB_OUTPUT


  build-debian:
    name: Debian
    runs-on: ubuntu-latest
    needs: get-version

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: cd contrib/ci/ && podman build -t pomidaq -f Dockerfile-debian .

    - name: Build
      run: |
        podman run -t -e COMPILER_VENDOR=$CVENDOR -e CC=gcc -e CXX=g++ \
            -e DEBEMAIL=no-reply@physiologie.uni-heidelberg.de \
            -v `pwd`:/build pomidaq ./contrib/ci/cibuild.sh

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v6
      with:
        name: pomidaq_${{ needs.get-version.outputs.version }}.debian13_amd64.zip
        path: pomidaq_*.deb


  build-ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    needs: get-version

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: cd contrib/ci/ && podman build -t pomidaq -f Dockerfile-ubuntu .

    - name: Build
      run: |
        podman run -t -e COMPILER_VENDOR=$CVENDOR -e CC=gcc -e CXX=g++ \
            -e DEBEMAIL=no-reply@physiologie.uni-heidelberg.de \
            -v `pwd`:/build pomidaq ./contrib/ci/cibuild.sh

    - name: Upload Ubuntu package artifact
      uses: actions/upload-artifact@v6
      with:
        name: pomidaq_${{ needs.get-version.outputs.version }}.ubuntu24.04_amd64.zip
        path: pomidaq_*.deb


  build-windows:
    name: Windows
    runs-on: windows-latest
    needs: get-version
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        pacboy: >-
          git
          cmake
          ninja
          gcc:p
          python
          librsvg:p
          icoutils:p
          appstream:p
          qt6-base:p
          qt6-svg:p
          opencv:p
          ffmpeg:p
          pybind11:p
          python-numpy:p

    - name: Configure
      run: |
        cmake -GNinja -Bbuild \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/PoMiDAQ-${{ needs.get-version.outputs.version }}" \
          -DPython3_EXECUTABLE="$(which python3)" \
          -DGUI=ON \
          -DPYTHON=ON

    - name: Build
      run: cmake --build build

    - name: Install & Bundle
      run: |
        cmake --build build --target install

        cd $GITHUB_WORKSPACE
        DEPLOY_DIR=$GITHUB_WORKSPACE/PoMiDAQ-${{ needs.get-version.outputs.version }}

        windeployqt \
          --no-quick-import \
          --no-translations \
          $DEPLOY_DIR/bin/pomidaq.exe

        # Copy DLLs
        ldd $DEPLOY_DIR/bin/pomidaq.exe \
          | awk '/\/ucrt64\/bin/ { print $3 }' \
          | while read -r dll; do
                install -v -p "$dll" $DEPLOY_DIR/bin/
            done

        # Misc
        cp LICENSE $DEPLOY_DIR/LICENSE.txt
        cp README.md $DEPLOY_DIR/
        cp contrib/LICENSES.3rd-party $DEPLOY_DIR/LICENSES_3rd-party.txt

        # Cleanup
        rm -rf $DEPLOY_DIR/cmake

        # move deploy dir into subdirectory
        mkdir -p $GITHUB_WORKSPACE/win64-deploy
        mv $DEPLOY_DIR $GITHUB_WORKSPACE/win64-deploy/

    - name: Build installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: contrib/win-installer.iss
        options: >-
          /DMyAppVersion=${{ needs.get-version.outputs.version }} /DMyAppVersionNumeric=${{ needs.get-version.outputs.version-numeric }} /DDeployDir=..\win64-deploy\PoMiDAQ-${{ needs.get-version.outputs.version }}

    - name: Upload Windows installer
      uses: actions/upload-artifact@v6
      with:
        name: PoMiDAQ-${{ needs.get-version.outputs.version }}_setup_win64
        path: contrib/output/PoMiDAQ-*_Setup_win64.exe

    - name: Upload Windows build as ZIP
      uses: actions/upload-artifact@v6
      with:
        name: PoMiDAQ-${{ needs.get-version.outputs.version }}_win64
        path: win64-deploy/
