#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define PROTOCOL_I2C           -2
#define PROTOCOL_SPI           -3
#define SEND_COMMAND_VALUE_H   -5
#define SEND_COMMAND_VALUE_L   -6
#define SEND_COMMAND_VALUE     -6
#define SEND_COMMAND_VALUE_H16 -7
#define SEND_COMMAND_VALUE_H24 -8
#define SEND_COMMAND_VALUE2_H  -9
#define SEND_COMMAND_VALUE2_L  -10
#define SEND_COMMAND_ERROR     -20

#endif // DEFINITIONS_H
